@extends('layouts.admin')
@section('content')
<div class="crumb">OPERATIONS / ORDERS</div><div class="topline"><h1>Đơn hàng</h1></div>
<section class="panel">
<form class="form-inline" method="GET"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Mã đơn, tên, email, SĐT"><select name="status"><option value="">Mọi trạng thái</option>@foreach(['pending','confirmed','packing','preparing','shipping','completed','cancelled'] as $value)<option value="{{ $value }}" @selected(($filters['status'] ?? '')===$value)>{{ \App\Support\UiLabels::orderStatus($value) }}</option>@endforeach</select><select name="payment_status"><option value="">Mọi thanh toán</option>@foreach(['pending','paid','failed'] as $value)<option value="{{ $value }}" @selected(($filters['payment_status'] ?? '')===$value)>{{ \App\Support\UiLabels::paymentStatus($value) }}</option>@endforeach</select><input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"><input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}"><button class="btn lime">LỌC</button><a class="btn" href="{{ route('admin.orders.index') }}">XOÁ LỌC</a></form>
<table class="table"><thead><tr><th>MÃ ĐƠN</th><th>KHÁCH HÀNG / SĐT</th><th>NGÀY</th><th>THANH TOÁN</th><th>TRẠNG THÁI</th><th>GHN</th><th>TỔNG</th><th></th></tr></thead><tbody>
@forelse($orders as $order)<tr><td><a class="lime-link" href="{{ route('admin.orders.show',$order) }}"><b>{{ $order->number }}</b></a><div class="muted">{{ $order->items->count() }} sản phẩm</div></td><td>{{ $order->user?->name ?? $order->recipient_name }}<br><span class="muted">{{ $order->recipient_phone }}</span></td><td>{{ $order->created_at?->format('d/m/Y H:i') }}</td><td>{{ \App\Support\UiLabels::paymentMethod($order->payment_method) }}<br><span class="muted">{{ \App\Support\UiLabels::paymentStatus($order->payment_status) }}</span></td><td><span class="status {{ $order->status }}">{{ \App\Support\UiLabels::orderStatus($order->status) }}</span></td><td>{{ $order->ghn_order_code ?? '—' }}<br><span class="muted">{{ \App\Support\UiLabels::ghnStatus($order->shipping_status) }}</span></td><td><b>{{ number_format($order->total) }} ₫</b></td><td><a class="btn small" href="{{ route('admin.orders.show',$order) }}">CHI TIẾT</a></td></tr>@empty<tr><td colspan="8" class="muted">Chưa có đơn hàng phù hợp.</td></tr>@endforelse
</tbody></table><div style="margin-top:18px">{{ $orders->links() }}</div></section>
@endsection
