@extends('layouts.admin')
@section('content')
<div class="crumb">OPERATIONS / ORDERS / {{ $order->number }}</div><div class="topline"><h1>{{ $order->number }}</h1><a class="btn" href="{{ route('admin.orders.index') }}">← QUAY LẠI</a></div>
<div class="dashboard-grid"><div><section class="panel"><div class="toolbar"><b>Sản phẩm</b><span class="status {{ $order->status }}">{{ \App\Support\UiLabels::orderStatus($order->status) }}</span></div><table class="table"><tbody>@foreach($order->items as $item)<tr><td>@php($image=$item->variant?->product?->images?->first()) @if($image)<img class="item-image" src="{{ str_starts_with($image->path,'http')?$image->path:asset('storage/'.$image->path) }}" alt="">@endif</td><td><b>{{ $item->product_name }}</b><br><span class="muted">{{ $item->variant?->color ?? $item->color }} / {{ $item->variant?->size ?? $item->size }} · SKU {{ $item->sku }}</span></td><td>{{ $item->quantity }} × {{ number_format($item->unit_price) }} ₫</td><td><b>{{ number_format($item->unit_price * $item->quantity) }} ₫</b></td></tr>@endforeach</tbody></table></section>
<section class="panel" style="margin-top:16px"><b>Lịch sử trạng thái</b><div class="timeline" style="margin-top:18px">@forelse($order->statusHistories->sortBy('created_at') as $event)<article><b>{{ \App\Support\UiLabels::orderStatus($event->from_status) }} → {{ \App\Support\UiLabels::orderStatus($event->to_status) }}</b><div class="muted">{{ $event->created_at?->format('d/m/Y H:i') }} · {{ $event->actor?->name ?? strtoupper($event->source) }}</div></article>@empty<p class="muted">Chưa có lịch sử chuyển trạng thái.</p>@endforelse</div></section></div><div>
<section class="panel"><b>Cập nhật đơn</b><p class="muted">{{ \App\Support\UiLabels::orderStatus($order->status) }} · GHN {{ \App\Support\UiLabels::ghnStatus($order->shipping_status) }}</p><div class="actions">@php($next=['pending'=>'confirmed','confirmed'=>'packing','packing'=>'shipping'][$order->status] ?? null) @if($next)<form method="POST" action="{{ route('admin.orders.status',$order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $next }}"><button class="btn lime">{{ \App\Support\UiLabels::orderStatus($next) }}</button></form>@endif @if($order->ghn_order_code)<form method="POST" action="{{ route('admin.orders.sync-ghn',$order) }}">@csrf<button class="btn">ĐỒNG BỘ GHN</button></form>@endif @if(in_array($order->status,['pending','confirmed','packing'],true))<form method="POST" action="{{ route('admin.orders.status',$order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="cancelled"><button class="btn danger">HUỶ ĐƠN</button></form>@endif @if(Route::has('admin.orders.manual-complete'))<form method="POST" action="{{ route('admin.orders.manual-complete',$order) }}">@csrf<button class="btn">XÁC NHẬN GIAO THÀNH CÔNG</button></form>@endif</div></section>
<section class="panel" style="margin-top:16px"><b>Người nhận</b><p>{{ $order->recipient_name }}<br>{{ $order->recipient_phone }}<br>{{ $order->address_line }}</p><p class="muted">{{ $order->province }} · {{ $order->district }} · {{ $order->ward }}</p></section>
<section class="panel" style="margin-top:16px"><b>Tổng tiền & thanh toán</b><p class="muted">Tạm tính <span style="float:right">{{ number_format($order->subtotal) }} ₫</span></p><p class="muted">Giảm giá <span style="float:right">−{{ number_format($order->discount) }} ₫</span></p><p class="muted">Phí vận chuyển <span style="float:right">{{ number_format($order->shipping_fee) }} ₫</span></p><hr style="border-color:var(--line)"><p><b>Tổng</b><b style="float:right;color:var(--lime)">{{ number_format($order->total) }} ₫</b></p><p class="muted">{{ \App\Support\UiLabels::paymentMethod($order->payment_method) }} · {{ \App\Support\UiLabels::paymentStatus($order->payment_status) }}</p>@if($order->ghn_order_code)<p>GHN: <b>{{ $order->ghn_order_code }}</b><br><span class="muted">Phí GHN: {{ number_format($order->ghn_total_fee ?? 0) }} ₫</span></p>@endif @if($order->completed_at)<p class="muted">Hoàn tất: {{ $order->completed_at->format('d/m/Y H:i') }}{{ $order->completedBy ? ' · '.$order->completedBy->name : '' }}</p>@endif</section></div></div>
@endsection
